name: Enviar Relatório por Email

on:
  # Agenda: executar todos os dias às 9h (horário de Brasília = 12h UTC)
  schedule:
    - cron: '0 12 * * *'
  
  # Permite executar manualmente
  workflow_dispatch:

jobs:
  gerar-e-enviar:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v3
      
      - name: 🔧 Configurar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
      - name: Install system dependencies for ragg
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libwebp-dev
      - name: 📦 Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            pandoc \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra
      
      - name: 📚 Instalar pacotes do R
        run: |
          install.packages(c("rmarkdown", "tidyverse", "knitr"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      - name: 📄 Gerar relatório PDF
        run: |
          Rscript gerar_pdf.R
      
      - name: ✅ Verificar PDF gerado
        run: |
          if [ -f "program_conecta_campinas.pdf" ]; then
            echo "✓ PDF encontrado!"
            ls -lh program_conecta_campinas.pdf
          else
            echo "✗ PDF não foi gerado!"
            exit 1
          fi
      
      - name: 📧 Enviar email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: Programação Conecta - Prefeitura
          to: rikibragada@gmail.com
          from: hkbragada@gmail.com
          body: |
            Bom dia,
            
            Segue em anexo a programação diária das manutenções previstas para a cidade de Campinas.
            
            Bot - HK CONSULTORIA
          attachments: program_conecta_campinas.pdf
          convert_markdown: true
      
      - name: ✅ Concluído
        run: |
          echo "✓ Email enviado com sucesso!"
          echo "Data/hora: $(date)"
