name: Enviar Email com PDF do S3

on:
  workflow_dispatch: # Permite execução manual para testes

jobs:
  send_email_with_attachment:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar credenciais AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 2. Baixar o arquivo PDF do S3
      - name: Download PDF from S3
        run: |
          aws s3 cp s3://automacao-conecta/program_conecta_campinas.pdf ./program_conecta_campinas.pdf
          ls -lh program_conecta_campinas.pdf
          echo "Arquivo baixado com sucesso!"

      # 3. Verificar se o arquivo existe
      - name: Verify PDF file
        run: |
          if [ -f "./program_conecta_campinas.pdf" ]; then
            echo "✅ PDF file exists"
            echo "File size: $(du -h program_conecta_campinas.pdf | cut -f1)"
          else
            echo "❌ PDF file not found!"
            exit 1
          fi

      # 4. Enviar o Email com o Anexo
      - name: Send Email with PDF
        uses: dawidd6/action-send-mail@v3
        with:
          # Configuração SMTP para Brevo (Sendinblue)
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: true  # TLS/STARTTLS
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}

          # Detalhes do Email
          subject: Relatório PDF Anexado - Conecta Campinas
          to: hkbragada@gmail.com
          from: 98ec0c001@smtp-brevo.com
          
          # Corpo HTML para melhor formatação
          html_body: |
            <html>
            <body>
              <p>Prezado(a),</p>
              <p>O PDF solicitado, <strong>"program_conecta_campinas.pdf"</strong>, está anexado a este email.</p>
              <p>Atenciosamente,<br>
              <em>GitHub Actions - Sistema Conecta</em></p>
            </body>
            </html>

          # ANEXO: caminho relativo ao workspace
          attachments: ./program_conecta_campinas.pdf
          
          # Prioridade do email
          priority: normal

      # 5. Confirmação de sucesso
      - name: Success notification
        if: success()
        run: |
          echo "✅ Email enviado com sucesso para hkbragada@gmail.com"
          echo "Data/Hora: $(date)"
